@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>PasswordAuthMethod</b>\n<size:10>it.matlice.ingsw.model.auth.password" as it.matlice.ingsw.model.auth.password.PasswordAuthMethod  [[../../../../../../it/matlice/ingsw/model/auth/password/PasswordAuthMethod.html{it.matlice.ingsw.model.auth.password.PasswordAuthMethod}]] {
{static} +String MAC_ALGO
{static} +Pattern PASSWORD_SEC_REGEX
{static} +int SALT_LENGTH
-PasswordAuthenticable user
-Random random_source
+PasswordAuthMethod(PasswordAuthenticable user)
{static} +AuthData getAuthData(String password)
{static} +boolean isPasswordValid(String password)
+Authenticable getUser()
+void setPassword(String password,boolean skipComplexityCheck)
+void setPassword(String password)
+boolean performAuthentication(AuthData data)
-byte getNewSalt()
-byte getPasswordHash(byte salt,String password)
}


interface "<b><size:14>PasswordAuthenticable</b>\n<size:10>it.matlice.ingsw.model.auth.password" as it.matlice.ingsw.model.auth.password.PasswordAuthenticable  [[../../../../../../it/matlice/ingsw/model/auth/password/PasswordAuthenticable.html{it.matlice.ingsw.model.auth.password.PasswordAuthenticable}]] {
}

hide it.matlice.ingsw.model.auth.password.PasswordAuthenticable fields
hide it.matlice.ingsw.model.auth.password.PasswordAuthenticable methods

it.matlice.ingsw.model.auth.password.PasswordAuthMethod -->  "user" it.matlice.ingsw.model.auth.password.PasswordAuthenticable



interface "<b><size:14>AuthMethod</b>\n<size:10>it.matlice.ingsw.model.auth" as it.matlice.ingsw.model.auth.AuthMethod  [[../../../../../../it/matlice/ingsw/model/auth/AuthMethod.html{it.matlice.ingsw.model.auth.AuthMethod}]] #white {
}

hide it.matlice.ingsw.model.auth.AuthMethod fields
hide it.matlice.ingsw.model.auth.AuthMethod methods

it.matlice.ingsw.model.auth.password.PasswordAuthMethod ..|> it.matlice.ingsw.model.auth.AuthMethod

interface "<b><size:14>AuthData</b>\n<size:10>it.matlice.ingsw.model.auth" as it.matlice.ingsw.model.auth.AuthData  [[../../../../../../it/matlice/ingsw/model/auth/AuthData.html{it.matlice.ingsw.model.auth.AuthData}]] #white {
}

hide it.matlice.ingsw.model.auth.AuthData fields
hide it.matlice.ingsw.model.auth.AuthData methods

it.matlice.ingsw.model.auth.password.PasswordAuthMethod ..> it.matlice.ingsw.model.auth.AuthData

interface "<b><size:14>Authenticable</b>\n<size:10>it.matlice.ingsw.model.auth" as it.matlice.ingsw.model.auth.Authenticable  [[../../../../../../it/matlice/ingsw/model/auth/Authenticable.html{it.matlice.ingsw.model.auth.Authenticable}]] #white {
}

hide it.matlice.ingsw.model.auth.Authenticable fields
hide it.matlice.ingsw.model.auth.Authenticable methods

it.matlice.ingsw.model.auth.password.PasswordAuthMethod ..> it.matlice.ingsw.model.auth.Authenticable


@enduml
