@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>PasswordAuthData</b>\n<size:10>it.matlice.ingsw.model.auth.password" as it.matlice.ingsw.model.auth.password.PasswordAuthData  [[../../../../../../it/matlice/ingsw/model/auth/password/PasswordAuthData.html{it.matlice.ingsw.model.auth.password.PasswordAuthData}]] {
-String password
+PasswordAuthData(String password)
+String password()
+boolean equals(Object obj)
+int hashCode()
+String toString()
}


interface "<b><size:14>AuthData</b>\n<size:10>it.matlice.ingsw.model.auth" as it.matlice.ingsw.model.auth.AuthData  [[../../../../../../it/matlice/ingsw/model/auth/AuthData.html{it.matlice.ingsw.model.auth.AuthData}]] #white {
}

hide it.matlice.ingsw.model.auth.AuthData fields
hide it.matlice.ingsw.model.auth.AuthData methods

it.matlice.ingsw.model.auth.password.PasswordAuthData ..|> it.matlice.ingsw.model.auth.AuthData


@enduml
