@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
interface "<b><size:14>PasswordAuthenticable</b>\n<size:10>it.matlice.ingsw.model.auth.password" as it.matlice.ingsw.model.auth.password.PasswordAuthenticable  [[../../../../../../it/matlice/ingsw/model/auth/password/PasswordAuthenticable.html{it.matlice.ingsw.model.auth.password.PasswordAuthenticable}]] {
{abstract} +byte getPasswordHash()
{abstract} +byte getPasswordSalt()
{abstract} +void setPassword(byte password)
{abstract} +void setSalt(byte salt)
}


interface "<b><size:14>Authenticable</b>\n<size:10>it.matlice.ingsw.model.auth" as it.matlice.ingsw.model.auth.Authenticable  [[../../../../../../it/matlice/ingsw/model/auth/Authenticable.html{it.matlice.ingsw.model.auth.Authenticable}]] #white {
}

hide it.matlice.ingsw.model.auth.Authenticable fields
hide it.matlice.ingsw.model.auth.Authenticable methods

it.matlice.ingsw.model.auth.password.PasswordAuthenticable --|> it.matlice.ingsw.model.auth.Authenticable

class "<b><size:14>PasswordAuthMethod</b>\n<size:10>it.matlice.ingsw.model.auth.password" as it.matlice.ingsw.model.auth.password.PasswordAuthMethod  [[../../../../../../it/matlice/ingsw/model/auth/password/PasswordAuthMethod.html{it.matlice.ingsw.model.auth.password.PasswordAuthMethod}]] {
}

hide it.matlice.ingsw.model.auth.password.PasswordAuthMethod fields
hide it.matlice.ingsw.model.auth.password.PasswordAuthMethod methods

it.matlice.ingsw.model.auth.password.PasswordAuthMethod -->  "user" it.matlice.ingsw.model.auth.password.PasswordAuthenticable

class "<b><size:14>CustomerUserImpl</b>\n<size:10>it.matlice.ingsw.model.data.impl.jdbc.types" as it.matlice.ingsw.model.data.impl.jdbc.types.CustomerUserImpl  [[../../../../../../it/matlice/ingsw/model/data/impl/jdbc/types/CustomerUserImpl.html{it.matlice.ingsw.model.data.impl.jdbc.types.CustomerUserImpl}]] #white {
}

hide it.matlice.ingsw.model.data.impl.jdbc.types.CustomerUserImpl fields
hide it.matlice.ingsw.model.data.impl.jdbc.types.CustomerUserImpl methods

it.matlice.ingsw.model.data.impl.jdbc.types.CustomerUserImpl ..|> it.matlice.ingsw.model.auth.password.PasswordAuthenticable

class "<b><size:14>ConfiguratorUserImpl</b>\n<size:10>it.matlice.ingsw.model.data.impl.jdbc.types" as it.matlice.ingsw.model.data.impl.jdbc.types.ConfiguratorUserImpl  [[../../../../../../it/matlice/ingsw/model/data/impl/jdbc/types/ConfiguratorUserImpl.html{it.matlice.ingsw.model.data.impl.jdbc.types.ConfiguratorUserImpl}]] #white {
}

hide it.matlice.ingsw.model.data.impl.jdbc.types.ConfiguratorUserImpl fields
hide it.matlice.ingsw.model.data.impl.jdbc.types.ConfiguratorUserImpl methods

it.matlice.ingsw.model.data.impl.jdbc.types.ConfiguratorUserImpl ..|> it.matlice.ingsw.model.auth.password.PasswordAuthenticable


@enduml
