@startuml

skinparam ClassAttributeIconSize 0
'skinparam groupInheritance 2
skinparam linetype ortho
hide empty members

package model #FFFFFF {

    class Model <<singleton>> {
        + createConfigurator(auth: Authentication, username: String)
        + createHierarchy(auth: Authentication, root: Category)
        + showHierarchies()
        + showConfParameters()
        + editConfParameters(...)
    }

    class AuthImpl implements Authentication {
        - AuthImpl(user: User)
    }

    interface Authentication {
        + getUser(): User
        + getLoginTime(): int
        + getExpirationTime(): int
        + isExpired(): bool
    }

    class Settings {}
}

abstract class User

interface UserFactory
interface CategoryFactory
interface HierarchyFactory
interface SettingsFactory

AuthImpl --> "1" User
Model +-down-> AuthImpl

Model ..> Settings

Model .down.> UserFactory
Model .down.> CategoryFactory
Model .down.> HierarchyFactory
Model .down.> SettingsFactory

@enduml