@startuml

:Utente di sistema: as user
:Configuratore: as conf

conf -up-|> user
conf --> (Accesso Configuratore)
conf --> (Creazione gerarchia)

conf --> (Creazione nuovo \naccount configuratore)
conf --> (Visualizzazione gerarchia)

(Accesso Configuratore) ..> (Accesso utente): <<include>>
(Creazione gerarchia) ..> (Accesso Configuratore): <<include>>

:Fruitore: as fruit

fruit -up-|> user

(Configurazione parametri)
(Registrazione fruitore)

conf --> (Configurazione parametri)
fruit --> (Visualizzazione informazioni)
fruit --> (Registrazione fruitore)
fruit --> (Accesso utente)
(Configurazione parametri) ..> (Accesso Configuratore) : <<include>>

fruit --> (Pubblicazione articolo)
fruit --> (Ritiro offerta)
fruit --> (Visualizzazione offerte \nper categoria)
conf --> (Visualizzazione offerte \nper categoria)
fruit --> (Visualizzazione offerte \ndell'utente)


'VERSIONE 4 ==========================================

(Proposta di scambio) #pink;line:red;text:red
(Accettazione scambio) #pink;line:red;text:red
(Accettazione appuntamento) #pink;line:red;text:red
(Visualizzazione offerta \nin scambio) #pink;line:red;text:red
(Visualizzazione offerte \nchiuse e in scambio) #pink;line:red;text:red

fruit --> (Proposta di scambio) #red;text:red
fruit --> (Accettazione scambio) #red;text:red
fruit --> (Accettazione appuntamento) #red;text:red
fruit -up-> (Visualizzazione offerta \nin scambio) #red;text:red
conf -left-> (Visualizzazione offerte \nchiuse e in scambio) #red;text:red

(Accettazione appuntamento) ..> (Accettazione scambio) #red;text:red : <<include>>
(Accettazione scambio) ..> (Proposta di scambio) #red;text:red : <<include>>

'(Visualizzazione offerte \nchiuse e in scambio) -[hidden]- (Visualizzazione offerte \nper categoria)
(Registrazione fruitore) -[hidden]- (Pubblicazione articolo)
'(Pubblicazione articolo) -[hidden]- (Ritiro offerta)
'(Accettazione appuntamento) -[hidden]- (Ritiro offerta)
(Registrazione fruitore) -[hidden]- (Visualizzazione offerte \ndell'utente)
'(Accettazione appuntamento) -[hidden]- (Visualizzazione offerte \ndell'utente)
'(Visualizzazione offerte \nchiuse e in scambio) -[hidden]- (Visualizzazione offerte \nper categoria)
'(Visualizzazione gerarchia) -[hidden]- (Creazione nuovo \naccount configuratore)

@enduml