@startuml

:Utente di sistema: as user
:Configuratore: as conf
:Amministratore: as adm

conf -up-|> user
conf --> (Accesso Configuratore)
conf --> (Creazione gerarchia)

adm --> (Creazione nuovo \naccount configuratore)

(Accesso Configuratore) ..> (Accesso utente): <<include>>

@enduml