@startuml

:Utente di sistema: as user
:Configuratore: as conf

conf -up-|> user
conf --> (Accesso Configuratore)
conf --> (Creazione gerarchia)

conf --> (Creazione nuovo \naccount configuratore)
conf --> (Visualizzazione gerarchia)

(Accesso Configuratore) ..> (Accesso utente): <<include>>
(Creazione gerarchia) ..> (Accesso Configuratore): <<include>>
(Visualizzazione gerarchia) ..> (Accesso Configuratore): <<include>>

@enduml