@startuml

'skinparam Linetype ortho

class HashMap<String, Object>{}

abstract class Offer extends HashMap{
    + getName(): String
    + getOwner(): User
    + getStatus(): OfferStatus
    + getCategory(): LeafCategory
}

class OfferImpl extends Offer{
    - id: Integer
    - name: String
    - status: String
--
    + <<getter>>
    + <<setter>>
    + {static} findById(id: Integer): OfferImpl
    + update(): void
    + delete(): void
    + <<other db methods>>
    + populateDatabaseFields(): void
}

abstract class User{}
abstract class Category{}
class JDBCConnection{}
class TypeDefinition{
    --
    + required(): bool
    + getType(): TypeAssociation
}

class TypeAssociation<T>{
    --
    + serialize(o: T): String
    + deserialize(s: String): T
}

class OfferFactoryImpl{
}

HashMap -[hidden]left- Offer
Offer -[hidden]down- OfferImpl
JDBCConnection -[hidden]down- TypeDefinition

OfferImpl -down-> User
OfferImpl -down-> Category
OfferImpl "1  " *-- Offer
OfferImpl -right-> JDBCConnection
OfferImpl -right- TypeDefinition

TypeDefinition --> TypeAssociation
OfferFactoryImpl --> OfferImpl: crea >

@enduml