@startuml
skinparam conditionStyle diamond


start

-> username, password;

:SELECT username FROM users AS user_ref;

if (hmac(salt, password) == user_ref.password_hash) then
    stop
else ([else])
    end
endif



@enduml