@startuml

skinparam ClassAttributeIconSize 0
'skinparam groupInheritance 2
skinparam linetype ortho
hide empty members

package controller #FFFFFF {

    class Controller <<singleton>> {
        + createConfigurator(auth: Authentication, username: String)
        + createHierarchy(auth: Authentication, root: Category)
        + showHierarchies()
        + showConfParameters()
        + editConfParameters(...)
        + createOffer(u: User, name: String, cat: LeafCategory, fields: Map<String, String>)
        + retractOffer(offer: Offer)
        + showOffersByUser(user: User)
        + showOpenOffersByCategory(category: LeafCategory)

        + importConfiguration(file: FileInputStream)
    }

    class AuthImpl implements Authentication {
        - AuthImpl(user: User)
    }

    interface Authentication {
        + getUser(): User
        + getLoginTime(): int
        + getExpirationTime(): int
        + isExpired(): bool
    }

    class Settings {}
}

abstract class User

interface UserFactory
interface CategoryFactory
interface HierarchyFactory
interface SettingsFactory
interface OfferFactory

AuthImpl --> "1" User
Controller +-down-> AuthImpl

Controller ..> Settings

Controller .up.> UserFactory
Controller .up.> CategoryFactory
Controller .up.> HierarchyFactory
Controller .up.> SettingsFactory
Controller .up.> OfferFactory

@enduml