@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>InvalidPasswordException</b>\n<size:10>it.matlice.ingsw.model.auth.exceptions" as it.matlice.ingsw.model.auth.exceptions.InvalidPasswordException  [[../../../../../../it/matlice/ingsw/model/auth/exceptions/InvalidPasswordException.html{it.matlice.ingsw.model.auth.exceptions.InvalidPasswordException}]] {
+InvalidPasswordException()
}


class "<b><size:14>Exception</b>\n<size:10>java.lang" as java.lang.Exception  #lightgrey {
}

hide java.lang.Exception fields
hide java.lang.Exception methods

it.matlice.ingsw.model.auth.exceptions.InvalidPasswordException --|> java.lang.Exception


@enduml
