@startuml

skinparam ClassAttributeIconSize 0
'skinparam groupInheritance 2
skinparam linetype ortho
hide empty members

package controller #FFFFFF {

    class Controller <<singleton>> {
        + createConfigurator(auth: Authentication, username: String)
        + createHierarchy(auth: Authentication, root: Category)
    }

    class AuthImpl implements Authentication

    interface Authentication {
        + getUser(): User
        + getLoginTime(): int
        + getExpirationTime(): int
        + isExpired(): bool
    }

    class Settings {}
}

abstract class User
abstract class Hierarchy

interface UserFactory
interface CategoryFactory
interface HierarchyFactory

AuthImpl --> "1" User
Controller "1 " o--right--> "1..n" Hierarchy
Controller +-down-> AuthImpl

Controller ..> Settings

Controller .down.> UserFactory
Controller .down.> CategoryFactory
Controller .down.> HierarchyFactory

AuthImpl -left[hidden]- Authentication
Hierarchy -[hidden]- UserFactory
UserFactory -[hidden]- CategoryFactory
CategoryFactory -[hidden]- HierarchyFactory


@enduml