@startuml

skinparam ClassAttributeIconSize 0
'skinparam groupInheritance 2
skinparam linetype ortho
hide empty members

interface PasswordAuthenticable

package data #FFFFFF {
    abstract class ConfiguratorUser
    interface UserFactory
    interface HierarchyFactory

    abstract class NodeCategory
    abstract class LeafCategory

    package impl.sqlite #FFFFFF {
        
        class CategoryDB {
            - categoryId: int
            - categoryName: String
        }

        class HierarchyDB {
            - hierarchyId: int
        }

        class UserDB {
            - username: String
            - password_hash: String
            - password_salt: String
            - type: String
        }

        class UserFactoryImpl implements UserFactory {

        }

        package types {
            interface CategoryImpl {
                + getDBData(): CategoryDB
            }

            class NodeCategoryImpl extends NodeCategory implements CategoryImpl
            class LeafCategoryImpl extends LeafCategory implements CategoryImpl

            class ConfiguratorUserImpl extends ConfiguratorUser implements PasswordAuthenticable

            class HierarchyFactoryImpl extends HierarchyFactory
            class UserFactoryImpl extends UserFactory
            class CaegoryFactoryImpl extends CategoryFactory

        }

    }

}

CategoryDB --> "0..1" CategoryDB: father
HierarchyDB --> "1" CategoryDB: root

CategoryImpl ..> CategoryDB

NodeCategory -[hidden]-> LeafCategory


@enduml