@startuml

skinparam ClassAttributeIconSize 0
'skinparam groupInheritance 2
skinparam linetype ortho
hide empty members

package model #FFFFFF {

    class Model <<singleton>> {
        + createConfigurator(auth: Authentication, username: String)
        + createHierarchy(auth: Authentication, root: Category)
        + showHierarchies()
    }

    class AuthImpl implements Authentication{
        - AuthImpl(user: User)
    }

    interface Authentication {
        + getUser(): User
        + getLoginTime(): int
        + getExpirationTime(): int
        + isExpired(): bool
    }

    class Settings {}
}

abstract class User
abstract class Hierarchy

interface UserFactory
interface CategoryFactory
interface HierarchyFactory

AuthImpl --> "1" User
Model "1 " o--right--> "1..n" Hierarchy
Model +-down-> AuthImpl

Model ..> Settings

Model .down.> UserFactory
Model .down.> CategoryFactory
Model .down.> HierarchyFactory

AuthImpl -left[hidden]- Authentication
Hierarchy -[hidden]- UserFactory
UserFactory -[hidden]- CategoryFactory
CategoryFactory -[hidden]- HierarchyFactory


@enduml