@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>CannotParseDayException</b>\n<size:10>it.matlice.ingsw.model.exceptions" as it.matlice.ingsw.model.exceptions.CannotParseDayException  [[../../../../../it/matlice/ingsw/model/exceptions/CannotParseDayException.html{it.matlice.ingsw.model.exceptions.CannotParseDayException}]] {
+CannotParseDayException()
}


class "<b><size:14>Exception</b>\n<size:10>java.lang" as java.lang.Exception  #lightgrey {
}

hide java.lang.Exception fields
hide java.lang.Exception methods

it.matlice.ingsw.model.exceptions.CannotParseDayException --|> java.lang.Exception


@enduml
