@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>DuplicateUserException</b>\n<size:10>it.matlice.ingsw.model.exceptions" as it.matlice.ingsw.model.exceptions.DuplicateUserException  [[../../../../../it/matlice/ingsw/model/exceptions/DuplicateUserException.html{it.matlice.ingsw.model.exceptions.DuplicateUserException}]] {
+DuplicateUserException()
}


class "<b><size:14>Exception</b>\n<size:10>java.lang" as java.lang.Exception  #lightgrey {
}

hide java.lang.Exception fields
hide java.lang.Exception methods

it.matlice.ingsw.model.exceptions.DuplicateUserException --|> java.lang.Exception


@enduml
