@startuml
skinparam conditionStyle diamond

group Verifica password 

    start

    -> username, password;

    :Select username from users as user_ref;

    if ("hash(hmac(salt, password)) == user_ref.password_hash") then
        stop
    else ([else])
        end
    endif

end group



@enduml