@startuml
skinparam linetype ortho

component it.matlice.ingsw.auth #FFFFFF{
    interface AuthMethod
    interface Authenticable
    interface AuthData
    component password #FFFFFF{
        interface "Password\nAuthenticable" as PasswordAuthenticable
        [PasswordAuthData] -- AuthData
        [PasswordAuthData] -[hidden]-( PasswordAuthenticable
        [PasswordAuthMethod] -- AuthMethod
        [PasswordAuthMethod] --( Authenticable
    } 
} 

component it.matlice.ingsw.data #FFFFFF{

    [User] -- Authenticable
    [Category]
    [Hierarchy]

    interface UserFactory
    interface CategoryFactory
    interface HierarchyFactory

    component impl.sqlite #FFFFFF{
        [UserFactoryImpl] -- UserFactory
        [CategoryFactoryImpl] -- CategoryFactory
        [HierarchyFactoryImpl] -- HierarchyFactory

        component types #FFFFFF{
            [ConfiguratorUserImpl] -up- PasswordAuthenticable
            [ConfiguratorUserImpl] -up-( AuthMethod
            [ConfiguratorUserImpl] -up-( AuthData

            [CategoryImpl]
            [HierarchyImpl]
        }

    }
}

component it.matlice.ingsw.controller #FFFFFF{

    interface Authentication

    [Controller.AuthImpl] -- Authentication
    [Controller] -( Authentication

    [Controller] -up-( CategoryFactory
    [Controller] -up-( HierarchyFactory
    [Controller] -up-( UserFactory
}

[Controller] +--> [Controller.AuthImpl]

[UserFactoryImpl] .up.> [ConfiguratorUserImpl]: creates
[CategoryFactoryImpl] .up.> [CategoryImpl]: creates
[HierarchyFactoryImpl] .up.> [HierarchyImpl]: creates

[ConfiguratorUserImpl] --|> User
[CategoryImpl] -up-|> Category
[HierarchyImpl] -up-|> Hierarchy


@enduml