package it.matlice.ingsw.controller;

public enum MenuType {
    LOGIN_ENTRY,
    LOGOUT_ENTRY,
    EXIT_ENTRY,
    REGISTER_ENTRY,
    PROPOSE_CHANGE_ENTRY,
    ACCEPT_CHANGE_ENTRY,
    REPLY_MESSAGE_ENTRY,
    ADD_NEW_ARTICLE_ENTRY,
    RETRIEVE_OPENED_OFFER_ENTRY,
    SHOW_OFFERS_ENTRY,
    SHOW_OFFERS_BY_CATEGORY_ENTRY,
    ADD_HIERARCHY_ENTRY,
    ADD_CATEGORY_ENTRY,
    SHOW_HIERARCHIES_ENTRY,
    SHOW_PARAMETERS_ENTRY,
    EDIT_PARAMETERS_ENTRY,
    IMPORT_CONFIGURATION_ENTRY,
    ADD_CONFIGURATOR_ENTRY,
    CHANGE_PASSWORD_ENTRY,
    RESTORE_ENTRY,
    SEND_NEW_PROPOSE_ENTRY,
    SAVE_EXIT_PROMPT,
    GO_BACK_TO_CATEGORY_LIST_ENTRY,
    ADD_NATIVE_FIELD_ENTRY,
    MANUALLY_ADD_CONFIGURATION_ENTRY,
    AUTO_ADD_CONFIGURATION_ENTRY,
    SAVE_ARTICLE_ENTRY


}
