package it.matlice.ingsw.controller;

public enum PromptType {
    SELECT_OPTION_PROMPT,
    SELECT_OPTION_AFTER_LOGIN_PROMPT,
    ADD_HIERARCHY_PROMPT,
    SELECT_FATHER_HIERARCHY_PROMPT,
    ADD_NATIVE_FIELD_PROMPT,
    IMPORT_CONFIGURATION_PROMPT,
    SELECT_PLACE_PROMPT,
    SELECT_TYPE_PROMPT,
    SELECT_FIELD_OR_SAVE_PROMPT,
    SELECT_CATEGORY_PROMPT,
    SELECT_CATEGORY_FOR_OFFERS_PROMPT,
    SELECT_OFFER_TO_PROPOSE_PROMPT,
    SELECT_OFFER_TO_ACCEPT_PROMPT,
    SELECT_MESSAGE_PROMPT,
    SELECT_OFFER_TO_RETRIEVE_PROMPT,
    SELECT_HIERARCHY_PROMPT,

    INSERT_FIELD_VALUE_PROMPT,
    INSERT_USERNAME,
    INSERT_PASSWORD,
    INSERT_NEW_PASSWORD,
    INSERT_REPEATED_PASSWORD,
    INSERT_CITY_FOR_AFFAIR,
    INSERT_PLACE_FOR_AFFAIR,
    INSERT_DAY_FOR_AFFAIR,
    INSERT_HOUR_FOR_AFFAIR,
    INSERT_HOUR_INTERVAL,
    INSERT_EXPIRATION_FOR_AFFAIR,
    INSERT_FIELD_NAME_PROMPT,
    INSERT_CATEGORY_NAME_PROMPT,
    INSERT_CATEGORY_DESCRIPTION_PROMPT,
    INSERT_NEW_ARTICLE_NAME,
    INSERT_Y_N_REQUIRED,

    EMPTY_PROMPT
}
