package it.matlice.ingsw.controller;

public enum PromptType {
    SELECT_OPTION_PROMPT,
    SELECT_OPTION_AFTER_LOGIN_PROMPT,
    ADD_HIERARCHY_PROMPT,
    SELECT_FATHER_HIERARCHY_PROMPT,
    ADD_NATIVE_FIELD_PROMPT,
    IMPORT_CONFIGURATION_PROMPT,
    SELECT_PLACE_PROMPT,
    SELECT_TYPE_PROMPT,
    SELECT_FIELD_OR_SAVE_PROMPT,
    SELECT_CATEGORY_PROMPT,
    SELECT_CATEGORY_FOR_OFFERS_PROMPT,
    SELECT_OFFER_TO_PROPOSE_PROMPT,
    SELECT_OFFER_TO_ACCEPT_PROMPT,
    SELECT_MESSAGE_PROMPT,
    SELECT_OFFER_TO_RETRIEVE_PROMPT,
    SELECT_HIERARCHY_PROMPT,
    EMPTY_PROMPT
}
