package it.matlice.ingsw.controller;

public enum WarningType {
    NEED_CHANGE_PASSWORD,
    SUCCESSFUL_REGISTRATION,
    NO_OFFERS_TO_EXCHANGE,
    NO_OFFERS_AVAILABLE_TO_EXCHANGE,
    SUCCESSFUL_OFFER_PROPOSAL,
    NO_ACCEPTABLE_OFFERS,
    NO_MESSAGES_TO_REPLY,
    SUCCESSFUL_ACCEPT_OFFER,
    NO_RETRACTABLE_OFFER,
    NO_LEAF_CATEGORIES_TO_SHOW,
    NO_HIERARCHIES,
    LOADING_CONFIG,
    CITY_NOT_OVERWRITABLE_SUCCESS,
    CITY_NOT_OVERWRITABLE,
    IMPORTING_HIERARCHIES,
    NO_EMPTY_NAME,
    OFFER_CREATED,
    NO_OFFER_FOUND,

}
