@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
interface "<b><size:14>MenuAction</b>\n<size:10>it.matlice.ingsw.view.menu" as it.matlice.ingsw.view.menu.MenuAction  [[../../../../../it/matlice/ingsw/view/menu/MenuAction.html{it.matlice.ingsw.view.menu.MenuAction}]] {
{abstract} +Object onUserSelect(Scanner in,PrintStream out,MenuEntry ref)
}


class "<b><size:14>MenuEntry</b>\n<size:10>it.matlice.ingsw.view.menu" as it.matlice.ingsw.view.menu.MenuEntry  [[../../../../../it/matlice/ingsw/view/menu/MenuEntry.html{it.matlice.ingsw.view.menu.MenuEntry}]] {
}

hide it.matlice.ingsw.view.menu.MenuEntry fields
hide it.matlice.ingsw.view.menu.MenuEntry methods

it.matlice.ingsw.view.menu.MenuEntry -->  "action" it.matlice.ingsw.view.menu.MenuAction


class "<b><size:14>PrintStream</b>\n<size:10>java.io" as java.io.PrintStream  #lightgrey {
}

hide java.io.PrintStream fields
hide java.io.PrintStream methods

it.matlice.ingsw.view.menu.MenuAction ..> java.io.PrintStream

it.matlice.ingsw.view.menu.MenuAction ..> it.matlice.ingsw.view.menu.MenuEntry

class "<b><size:14>Menu</b>\n<size:10>it.matlice.ingsw.view.menu" as it.matlice.ingsw.view.menu.Menu  [[../../../../../it/matlice/ingsw/view/menu/Menu.html{it.matlice.ingsw.view.menu.Menu}]] {
}

hide it.matlice.ingsw.view.menu.Menu fields
hide it.matlice.ingsw.view.menu.Menu methods

it.matlice.ingsw.view.menu.Menu ..> it.matlice.ingsw.view.menu.MenuAction


@enduml
