@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
package it.matlice.ingsw.view.menu [[../../../../../it/matlice/ingsw/view/menu/package-summary.html{it.matlice.ingsw.view.menu}]] #lightyellow {
}

class "<b><size:14>MenuEntry</b>" as it.matlice.ingsw.view.menu.MenuEntry  [[../../../../../it/matlice/ingsw/view/menu/MenuEntry.html{it.matlice.ingsw.view.menu.MenuEntry}]] {
}

hide it.matlice.ingsw.view.menu.MenuEntry fields
hide it.matlice.ingsw.view.menu.MenuEntry methods

interface "<b><size:14>MenuAction</b>" as it.matlice.ingsw.view.menu.MenuAction  [[../../../../../it/matlice/ingsw/view/menu/MenuAction.html{it.matlice.ingsw.view.menu.MenuAction}]] {
}

hide it.matlice.ingsw.view.menu.MenuAction fields
hide it.matlice.ingsw.view.menu.MenuAction methods

class "<b><size:14>Menu</b>" as it.matlice.ingsw.view.menu.Menu  [[../../../../../it/matlice/ingsw/view/menu/Menu.html{it.matlice.ingsw.view.menu.Menu}]] {
}

hide it.matlice.ingsw.view.menu.Menu fields
hide it.matlice.ingsw.view.menu.Menu methods

it.matlice.ingsw.view.menu.MenuEntry -->  "action" it.matlice.ingsw.view.menu.MenuAction
it.matlice.ingsw.view.menu.MenuEntry ..> it.matlice.ingsw.view.menu.MenuEntry
it.matlice.ingsw.view.menu.MenuAction ..> it.matlice.ingsw.view.menu.MenuEntry
it.matlice.ingsw.view.menu.Menu ..> it.matlice.ingsw.view.menu.MenuEntry
it.matlice.ingsw.view.menu.Menu -->  "last_entry" it.matlice.ingsw.view.menu.MenuEntry
it.matlice.ingsw.view.menu.Menu ..> it.matlice.ingsw.view.menu.MenuAction

@enduml
