@startuml

skinparam svgLinkTarget _parent
skinparam linetype ortho
set namespaceSeparator none
class "<b><size:14>EntryPoint</b>\n<size:10>it.matlice.ingsw" as it.matlice.ingsw.EntryPoint  [[../../../it/matlice/ingsw/EntryPoint.html{it.matlice.ingsw.EntryPoint}]] {
+EntryPoint()
{static} +void main(String args)
}



@enduml
